Development
DariusDangi/fwf-carturesti-internship-practice-dispatcher pull request #1
Opened 2024-08-23 11:47 UTC by DariusDangi

2024-08-23 12:49 UTC, FlorinBarsan requested changes
Please be more careful when working with selectors and clean what isn't needed. Overall nice implementation but pay more attention to small details!

2024-08-23 12:49 UTC, FlorinBarsan commented on ApplicationLayer/Chrome/Carturesti/Chrome_Carturesti_NavigateToSFBooks.xaml
verify selectors from this workflow:
attach window unified application target selector browser URL contains a GitHub address
delete all selectors that are not checked in targeting method
empty spaces and sketchy characters should be replaced with wildcards

2024-08-23 12:49 UTC, FlorinBarsan commented on ApplicationLayer/Chrome/eMAG/Chrome_eMAG_NavigateToSFBooks.xaml
verify selectors from this workflow:
delete all selectors that are not checked in targeting method
empty spaces and sketchy characters ([], &amp) should be replaced with wildcards

2024-08-23 12:49 UTC, FlorinBarsan commented on ApplicationLayer/Chrome/Carturesti/Chrome_Carturesti_ApplyFilters.xaml
select ascending price - anchor should have also a strict/fuzzy selector available, we shouldn't rely only on computer vision
- delete targeting method selectors that are not used
- select year of publish : what's the target there? I saw 2 anchors  in which one has as text the 2023 (which should be the target). Plus, idx used

2024-08-23 12:49 UTC, FlorinBarsan commented on ApplicationLayer/Chrome/Carturesti/Chrome_Carturesti_ExtractBooks.xaml
- "Do" sequence is redundant
- delete targeting method selectors that are not used

2024-08-23 12:49 UTC, FlorinBarsan commented on ApplicationLayer/Chrome/eMAG/Chrome_eMAG_ApplyFilters.xaml
- delete all selectors that are not checked in targeting method
- empty spaces and sketchy characters should be replaced with wildcards
- default retry scope name
- parkour from emag to carturesti website, please check selectors! 
![image](https://github.com/user-attachments/assets/ae573bc1-a010-455c-8764-5611f150bbe7)
- 
![image](https://github.com/user-attachments/assets/bb0a8012-31ac-4562-8805-31ac3a9b1467)

2024-08-23 12:49 UTC, FlorinBarsan commented on ApplicationLayer/Chrome/eMAG/Chrome_eMAG_ExtractBooks.xaml
- "Do" sequence is redundant
- delete targeting method selectors that are not used

2024-08-23 12:49 UTC, FlorinBarsan commented on ApplicationLayer/Chrome/eMAG/Chrome_eMAG_GetBookDetails.xaml
- delete targeting method selectors that are not used
- when creating unique reference, please store the format in config with something like "1_<datePlaceholder>_<TitleLength>", then on the actual code use Repalce method to replace the placeholders with the necessary info. This allow you to not have any hardcoded parameters

2024-08-23 12:49 UTC, FlorinBarsan commented on DataLayer/UploadQueueItems.xaml
you are using orchestrator service in this workflow to upload items, so I'd move this xaml file to ServiceLayer

2024-08-23 12:49 UTC, FlorinBarsan commented on Framework/CloseAllApplications.xaml
redundant sequences

2024-08-26 13:49 UTC, DariusDangi commented on ApplicationLayer/Chrome/Carturesti/Chrome_Carturesti_NavigateToSFBooks.xaml
Removed unsued selectors that are not checked in targeting methods, rectified selectors that had spaces/sketchy characters and removed the GitHub url from Use Browser activity

2024-08-26 13:54 UTC, DariusDangi commented on ApplicationLayer/Chrome/eMAG/Chrome_eMAG_NavigateToSFBooks.xaml
Removed unused selectors by targeting methods and modified the ones that are used by using wildcards.

2024-08-26 14:20 UTC, DariusDangi commented on ApplicationLayer/Chrome/Carturesti/Chrome_Carturesti_ApplyFilters.xaml
-Fixed the selector for ascending price. Tbh, i didn't even realize i had only computer vision on that activity.
-Removed unused selectors.
-The target is the checked checkbox. Those two anchors are for the verification of execution. The checked checkbox has a few attributes and that's why i chose to use two anchors.

2024-08-26 14:27 UTC, DariusDangi commented on ApplicationLayer/Chrome/Carturesti/Chrome_Carturesti_ExtractBooks.xaml
Removed unused selectors and the redundant "Do" sequence

2024-08-26 14:36 UTC, DariusDangi commented on ApplicationLayer/Chrome/eMAG/Chrome_eMAG_ApplyFilters.xaml
-Deleted all selectors that are not used
-Modified used selectors to replace spaces and sketchy characters with wildcards.
-Renamed activity that has default name

2024-08-26 14:37 UTC, DariusDangi commented on ApplicationLayer/Chrome/eMAG/Chrome_eMAG_ExtractBooks.xaml
Removed unused selectors and redundant "Do" sequence

2024-08-26 14:47 UTC, DariusDangi commented on ApplicationLayer/Chrome/eMAG/Chrome_eMAG_GetBookDetails.xaml
Created fields in config that will store a code (0 or 1) that will be used when building the unique reference.
Removed unused selectors.

2024-08-26 14:50 UTC, DariusDangi commented on DataLayer/UploadQueueItems.xaml
Moved UploadQueueItems workflow from DataLayer to ServiceLayer.

2024-08-26 14:52 UTC, DariusDangi commented on Framework/CloseAllApplications.xaml
Removed redundant sequences.

2024-08-28 07:32 UTC, FlorinBarsan approved these changes
Good job!

2024-08-28 07:32 UTC, merged